import streamlit as st
import pandas as pd
from datetime import datetime
from io import BytesIO
import plotly.express as px

# -----------------------------
# PROFESSIONAL HTML REPORT (PDF-style)
# -----------------------------
def generate_pdf_like_file(df):
    html = f"""
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body {{
                font-family: Arial, sans-serif;
                margin: 40px;
                color: #222;
            }}
            h1 {{
                text-align: center;
                color: #0047AB;
                margin-bottom: 5px;
            }}
            h3 {{
                text-align: center;
                color: #555;
                margin-top: 0px;
                margin-bottom: 25px;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }}
            th {{
                background-color: #0047AB;
                color: white;
                padding: 8px;
                font-size: 14px;
            }}
            td {{
                padding: 8px;
                border-bottom: 1px solid #ccc;
                font-size: 13px;
            }}
            tr:nth-child(even) {{
                background-color: #f2f6ff;
            }}
            .footer {{
                margin-top: 40px;
                text-align: center;
                font-size: 12px;
                color: #777;
            }}
        </style>
    </head>

    <body>
        <h1>POWER TRADE REPORT</h1>
        <h3>Auto Matched BUY->SELL & SELL->BUY Summary</h3>

        {df.to_html(index=False)}

        <div class="footer">
            Generated by POWER TRADE • {datetime.now().strftime("%d-%m-%Y %H:%M")}
        </div>
    </body>
    </html>
    """
    return html.encode("utf-8")

# -----------------------------
# PAGE CONFIG
# -----------------------------
st.set_page_config(
    page_title="Trade Analyzer",
    page_icon="📊",
    layout="wide"
)

# -----------------------------
# DARK MODE TOGGLE
# -----------------------------
dark_mode = st.sidebar.checkbox("🌙 Dark Mode", value=False)

# -----------------------------
# CUSTOM CSS (LIGHT + DARK)
# -----------------------------
if dark_mode:
    bg_color = "#0f172a"
    card_bg = "#1e293b"
    text_color = "#e5e7eb"
    accent = "#38bdf8"
else:
    bg_color = "#f5f7fa"
    card_bg = "#ffffff"
    text_color = "#111827"
    accent = "#0047AB"

st.markdown(f"""
<style>
body {{
    background-color: {bg_color};
    color: {text_color};
}}
.big-title {{
    font-size: 42px;
    font-weight: 800;
    color: {accent};
    text-align: center;
}}
.sub-title {{
    font-size: 20px;
    font-weight: 600;
    color: {text_color};
    text-align: center;
    margin-bottom: 30px;
}}
.box {{
    padding: 20px;
    background: {card_bg};
    border-radius: 12px;
    border: 1px solid #4b5563;
    box-shadow: 0px 3px 10px rgba(0,0,0,0.25);
    margin-bottom: 20px;
}}
.card {{
    padding: 18px;
    background: {card_bg};
    border-radius: 12px;
    border: 1px solid #4b5563;
    text-align: center;
    box-shadow: 0px 3px 10px rgba(0,0,0,0.25);
}}
.card-title {{
    font-size: 18px;
    font-weight: 600;
    color: {accent};
}}
.card-value {{
    font-size: 26px;
    font-weight: 700;
    color: {text_color};
}}
.logo-text {{
    font-size: 18px;
    font-weight: 700;
    color: {accent};
}}
</style>
""", unsafe_allow_html=True)

# -----------------------------
# HEADER + LOGO
# -----------------------------
logo_col, title_col = st.columns([1, 4])
with logo_col:
    st.markdown("<div class='logo-text'>⚡ POWER TRADE</div>", unsafe_allow_html=True)
with title_col:
    st.markdown("<div class='big-title'>📊 Trade Analyzer</div>", unsafe_allow_html=True)

st.markdown("<div class='sub-title'>BUY->SELL & SELL->BUY Auto Matching + Full PNL Dashboard</div>", unsafe_allow_html=True)

# -----------------------------
# INPUT BOXES
# -----------------------------
with st.container():
    st.markdown("<div class='box'>", unsafe_allow_html=True)

    time_limit = st.number_input("⏱ Time difference limit (minutes)", 1, 500, 30)
    pnl_limit = st.number_input("💰 Minimum PNL filter (₹)", 0, 1000000, 1000)

    uploaded_files = st.file_uploader(
        "📁 Excel file(s) upload karein (multi-file allowed)",
        type=["xlsx"],
        accept_multiple_files=True
    )

    st.markdown("</div>", unsafe_allow_html=True)

# -----------------------------
# PROCESSING MULTI-FILE
# -----------------------------
all_final_rows = []

if uploaded_files:
    for uploaded_file in uploaded_files:
        try:
            df_dict = pd.read_excel(uploaded_file, sheet_name=None)
            sheet_name = list(df_dict.keys())[0]
            df = df_dict[sheet_name]

            df.dropna(subset=['Order Time', 'Execute'], inplace=True)

            df['Order Time'] = pd.to_datetime(df['Order Time'], errors='coerce', dayfirst=True)
            df['Execute'] = pd.to_datetime(df['Execute'], errors='coerce').dt.time
            df['Date'] = df['Order Time'].dt.date

            df = df.sort_values(by=['Symbol', 'Order Time'])

            # BUY -> SELL
            buy_sell_results = []
            df_buy_sell = df.copy()

            for (client, symbol), group in df_buy_sell.groupby(['Client', 'Symbol']):
                buys = group[group['B/S'].str.upper() == 'BUY'].copy()
                sells = group[group['B/S'].str.upper() == 'SELL'].copy()

                for buy_idx, buy in buys.iterrows():
                    for sell_idx, sell in sells.iterrows():
                        buy_time = datetime.combine(buy['Order Time'].date(), buy['Execute'])
                        sell_time = datetime.combine(sell['Order Time'].date(), sell['Execute'])
                        time_diff = (sell_time - buy_time).total_seconds() / 60

                        if 0 <= time_diff <= time_limit and buy['Qty'] > 0 and sell['Qty'] > 0:
                            qty_traded = min(buy['Qty'], sell['Qty'])
                            profit_loss = round((sell['Order Price'] - buy['Order Price']) * qty_traded, 2)

                            buy_sell_results.append({
                                'Type': 'BUY->SELL',
                                'Client': client,
                                'Symbol': symbol,
                                'Date': buy['Date'],
                                'Buy Qty': qty_traded,
                                'Sell Qty': qty_traded,
                                'Buy Rate': buy['Order Price'],
                                'Sell Rate': sell['Order Price'],
                                'Rate Diff': round(sell['Order Price'] - buy['Order Price'], 2),
                                'Buy Time': buy_time.strftime("%H:%M:%S"),
                                'Sell Time': sell_time.strftime("%H:%M:%S"),
                                'Time Diff': f"{int(time_diff//60):02}:{int(time_diff%60):02}:00",
                                'Profit/Loss': profit_loss
                            })

                            buys.loc[buy_idx, 'Qty'] -= qty_traded
                            sells.loc[sell_idx, 'Qty'] -= qty_traded

                            if buys.loc[buy_idx, 'Qty'] == 0:
                                break

            buy_sell_df = pd.DataFrame(buy_sell_results)

            # SELL -> BUY
            sell_buy_results = []
            df_sell_buy = df.copy()

            for (client, symbol), group in df_sell_buy.groupby(['Client', 'Symbol']):
                sells = group[group['B/S'].str.upper() == 'SELL'].copy()
                buys = group[group['B/S'].str.upper() == 'BUY'].copy()

                for sell_idx, sell in sells.iterrows():
                    for buy_idx, buy in buys.iterrows():
                        sell_time = datetime.combine(sell['Order Time'].date(), sell['Execute'])
                        buy_time = datetime.combine(buy['Order Time'].date(), buy['Execute'])
                        time_diff = (buy_time - sell_time).total_seconds() / 60

                        if 0 <= time_diff <= time_limit and sell['Qty'] > 0 and buy['Qty'] > 0:
                            qty_traded = min(sell['Qty'], buy['Qty'])
                            profit_loss = round((sell['Order Price'] - buy['Order Price']) * qty_traded, 2)

                            sell_buy_results.append({
                                'Type': 'SELL->BUY',
                                'Client': client,
                                'Symbol': symbol,
                                'Date': sell['Date'],
                                'Buy Qty': qty_traded,
                                'Sell Qty': qty_traded,
                                'Sell Rate': sell['Order Price'],
                                'Buy Rate': buy['Order Price'],
                                'Rate Diff': round(sell['Order Price'] - buy['Order Price'], 2),
                                'Sell Time': sell_time.strftime("%H:%M:%S"),
                                'Buy Time': buy_time.strftime("%H:%M:%S"),
                                'Time Diff': f"{int(time_diff//60):02}:{int(time_diff%60):02}:00",
                                'Profit/Loss': profit_loss
                            })

                            sells.loc[sell_idx, 'Qty'] -= qty_traded
                            buys.loc[buy_idx, 'Qty'] -= qty_traded

                            if sells.loc[sell_idx, 'Qty'] == 0:
                                break

            sell_buy_df = pd.DataFrame(sell_buy_results)

            final_df = pd.concat([buy_sell_df, sell_buy_df], ignore_index=True)
            final_df = final_df.sort_values(by=['Symbol'])
            final_df = final_df[final_df['Profit/Loss'] >= pnl_limit]

            # SYMBOL-WISE BLANK ROW
            final_output = []
            prev_symbol = None

            for _, row in final_df.iterrows():
                if prev_symbol is not None and prev_symbol != row['Symbol']:
                    blank_row = {col: '' for col in final_df.columns}
                    blank_row['Profit/Loss'] = 0
                    final_output.append(blank_row)

                final_output.append(row.to_dict())
                prev_symbol = row['Symbol']

            final_df = pd.DataFrame(final_output)
            all_final_rows.append(final_df)

        except Exception as e:
            st.error(f"❌ Error in file {uploaded_file.name}: {e}")

# -----------------------------
# MERGE ALL FILES
# -----------------------------
if all_final_rows:
    final_df = pd.concat(all_final_rows, ignore_index=True)

    # SUMMARY
    symbol_summary = final_df.groupby('Symbol')['Profit/Loss'].sum().reset_index()
    client_summary = final_df.groupby('Client')['Profit/Loss'].sum().reset_index()
    grand_total = final_df['Profit/Loss'].sum()

    # TABS UI
    tab_summary, tab_trades, tab_charts = st.tabs(["📊 Summary", "📄 Trades", "📈 Charts"])

    # SUMMARY TAB
    with tab_summary:
        col1, col2, col3 = st.columns(3)
        col1.markdown(
            f"<div class='card'><div class='card-title'>Total Symbols</div>"
            f"<div class='card-value'>{symbol_summary.shape[0]}</div></div>",
            unsafe_allow_html=True
        )
        col2.markdown(
            f"<div class='card'><div class='card-title'>Total Clients</div>"
            f"<div class='card-value'>{client_summary.shape[0]}</div></div>",
            unsafe_allow_html=True
        )
        col3.markdown(
            f"<div class='card'><div class='card-title'>Grand Total PNL</div>"
            f"<div class='card-value'>₹ {grand_total:,.2f}</div></div>",
            unsafe_allow_html=True
        )

        st.subheader("📘 Symbol-wise Summary")
        st.dataframe(symbol_summary)

        st.subheader("📙 Client-wise Summary")
        st.dataframe(client_summary)

        # DOWNLOAD EXCEL + CSV + HTML REPORT
        output_xlsx = BytesIO()
        with pd.ExcelWriter(output_xlsx, engine='openpyxl') as writer:
            final_df.to_excel(writer, index=False, sheet_name='FINAL_TRADES')
            symbol_summary.to_excel(writer, index=False, sheet_name='SYMBOL_SUMMARY')
            client_summary.to_excel(writer, index=False, sheet_name='CLIENT_SUMMARY')
        output_xlsx.seek(0)

        st.download_button(
            label="⬇ Download Excel (with summaries)",
            data=output_xlsx,
            file_name="FINAL_TRADES.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )

        csv_data = final_df.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="⬇ Download Trades CSV",
            data=csv_data,
            file_name="FINAL_TRADES.csv",
            mime="text/csv"
        )

        pdf_data = generate_pdf_like_file(final_df)
        st.download_button(
            label="⬇ Download HTML Report (PDF-style)",
            data=pdf_data,
            file_name="FINAL_TRADES.html",
            mime="text/html"
        )

    # TRADES TAB
    with tab_trades:
        st.subheader("📄 All Trades (Auto-colored PNL)")
        styled_df = final_df.copy()
        st.dataframe(
            styled_df.style.apply(
                lambda s: [
                    'color: green; font-weight:bold' if (isinstance(v, (int, float)) and v > 0)
                    else ('color: red; font-weight:bold' if isinstance(v, (int, float)) and v < 0 else '')
                    for v in s
                ],
                subset=['Profit/Loss']
            )
        )

    # CHARTS TAB
    with tab_charts:
        st.subheader("📈 Symbol-wise PNL (Bar Chart)")
        sym_chart_df = symbol_summary[symbol_summary['Profit/Loss'] != 0]
        if not sym_chart_df.empty:
            fig_sym = px.bar(
                sym_chart_df,
                x='Symbol',
                y='Profit/Loss',
                title="Symbol-wise PNL",
                color='Profit/Loss',
                color_continuous_scale='Bluered'
            )
            st.plotly_chart(fig_sym, use_container_width=True)
        else:
            st.info("No symbol PNL data to show.")

        st.subheader("🧩 Client-wise PNL (Pie Chart)")
        cli_chart_df = client_summary[client_summary['Profit/Loss'] != 0]
        if not cli_chart_df.empty:
            fig_cli = px.pie(
                cli_chart_df,
                names='Client',
                values='Profit/Loss',
                title="Client-wise PNL Share"
            )
            st.plotly_chart(fig_cli, use_container_width=True)
        else:
            st.info("No client PNL data to show.")
else:
    st.info("📁 Please upload one or more Excel files to start analysis.")
